[project]
name = "rename-files-to-hash"
version = "3"
description = "Single python file to rename all files in a directory to their hash sums."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["blake3>=1.0.4"]
